### PR TITLE
Split the logic into 2 segments: cssNamespace and rawCssNamespace. Ad…

### PR DESCRIPTION
**Pull request by daniloster**
…ded analyser to grab css selector rules.

@nvanselow this is just a draft, pushing to let you know the progress. And, if you have some idea about how to fix the interpolated string template.

I will probably continue to work on this when I get back from holiday (2 weeks 😍)

### CODE REVIEW

**Comment by daniloster** [comment]
Found this website to help visualize the AST
https://astexplorer.net/

check the tree for:
```
const styled = { div() {} };

const MyStyledComponent = styled.div`
  background-color: ${props => (props.isDark ? 'red' : 'yellow')};
  color: ${props => (props.isDark ? 'white' : 'navy')};
  font-size: 30px;
  padding: 20px;

  & {
    border: 1px solid black;
  }
`;

export default MyStyledComponent;

```

**Comment by nvanselow** [comment]
I probably won't have a chance to take a look until the weekend. But I'll definitely try to dig into this more before you get back from holiday. Have a great break!

The astexplorer is great. I used that a lot when I was creating the first versions of this plugin. I'll check the use case you provided.

**Comment by daniloster** [comment]
Hi all, I got back from holiday, but, I still don't have time to look at this at the moment.

**Comment by nvanselow** [comment]
I spent some time with it and started some comments, but I didn't schedule long enough to really wrap my head around the problem and solution. Something wasn't sitting quite right, but I can't put my finger on it yet.

**Comment by nvanselow** [comment]
Thanks again for the contributions. I am going to close this in favor of the 1.0.0-rc version we recently published.

**Pull request closed without merging**
